version: "3.9"

name: "fyria"
services:
  database:
    image: postgres:17
    container_name: fyria_sso_db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      TZ: Europe/Paris
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - fyria_sso_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: fyria_sso_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

volumes:
  fyria_sso_data:

networks:
  postgres-network:
    driver: bridge
